### ISSUE TITLE
plugin searches for tsconfig from current path where eslint is run, instead of relative to eslintrc

### ISSUE THREAD

**Issue by jspradlin1-chwy** [Limegrass/eslint-plugin-import-alias#15]
```
Error: Error while loading rule '@limegrass/import-alias/import-alias': cannot find TSConfig or JSConfig, try assigning aliasConfigPath
Occurred while linting /Users/jspradlin1/IdeaProjects/hc-pet-insurance/src/test/js/services/cookies.service.test.ts
    at resolveTsconfigFilePath (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@limegrass/eslint-plugin-import-alias/build/alias-config.js:14:15)
    at Object.create (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/@limegrass/eslint-plugin-import-alias/build/rules/import-alias.js:172:77)
    at createRuleListeners (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/eslint/lib/linter/linter.js:910:21)
    at /Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/eslint/lib/linter/linter.js:1081:110
    at Array.forEach (<anonymous>)
    at runRules (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/eslint/lib/linter/linter.js:1018:34)
    at Linter._verifyWithoutProcessors (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/eslint/lib/linter/linter.js:1370:31)
    at Linter._verifyWithConfigArray (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/eslint/lib/linter/linter.js:1822:21)
    at Linter.verify (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/eslint/lib/linter/linter.js:1452:65)
    at Linter.verifyAndFix (/Users/jspradlin1/IdeaProjects/hc-pet-insurance/node_modules/eslint/lib/linter/linter.js:2083:29)
```

project structure:
```
src
  | - main/js
      | - eslintrc.js
      | - tsconfig.json
  | - test/js
      | - eslintrc.js
      | - tsconfig.json
```

if I run `npx eslint ./src/main/js`, the plugin fails to find `tsconfig.json`.  But, if I navigate to `src/main/js` and run `npx eslint .` then it finds it just fine, because it is searching relative to where eslint was called from (my current directory) instead of relative to where the eslintrc is.

The issue really presents itself when we attempt to commit and our pre-commit hook (husky + lintstaged) executes eslint from the project root and it fails no matter what.

**Comment by jspradlin1-chwy** [comment]
alternatively, it could also search for tsconfig relative to the file beint linted

**Comment by Limegrass** [comment]
Thanks for the suggestion. Searching from the file being linted sounds pretty reasonable off the top of my head -- I'll see if I can make some changes for that tonight/this weekend.

In the meantime, was it possible for you to work around the issue with an absolute path for `aliasConfigPath` option? I don't actually recall if that worked the way it was implemented, but it might look something this in the options
```json
{
    // ...
    "rules": {
        // ...
        "@limegrass/import-alias/import-alias": [
            "error",
            {
                "aliasConfigPath": "/absolute/path/to/tsconfig.json"
            }
        ]
    }
}
```

**Comment by jspradlin1-chwy** [comment]
it needs to work on all systems, not just mine, so I can't put in my custom absolute path, but I found this works, so long as you're using the javascript version of an eslintrc file:

```js
    '@limegrass/import-alias/import-alias': [
      'error',
      {
        aliasConfigPath: `${__dirname}/tsconfig.json`,
      },
    ],
```

**Comment by Limegrass** [comment]
Ah right, sorry about that. Nice find! I'll test out a fix tonight, had an idea off skimming the code.

**Comment by Limegrass** [comment]
The changes I had in mind were good for my simple test cases; however, one scenario that I haven't tested yet is usage of the `tsconfig` `extends` or `references` config options from nested files. I'm not sure whether or not the changes I have right now resolves the key mergers properly, so I'll have to delay pushing of these updates to tomorrow morning or the weekend to avoid risking any breakage for existing users since you were able to find a work around for now.

**Comment by richardjwinter** [comment]
@Limegrass I'm working in a monorepo and have placed all alias in the top level `tsconfig.json` and am using `extends` within each package `tsconfig.json`. This is now failing to error on relative imports. 

I've tried 

```
aliasConfigPath: `${__dirname}/../../tsconfig.json`,
```

but without success. Any ideas?
