### ISSUE TITLE
Support eslint 9

### ISSUE THREAD

**Issue by xamoulin** [Limegrass/eslint-plugin-import-alias#17]
Add support to version 9 of eslint.

**Comment by Limegrass** [comment]
Thanks for the issue. This has been in my radar, and I just hadn't got around to looking into whether the new config format was backwards compatible or not. Definitely helps to know that someone is trying to use it with ESLint 9 l, so I can start taking a look into this week when I find some time.

**Comment by Limegrass** [comment]
I should have updated this earlier, but I took a brief look at this last week. It seems like [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/issues/8211) and [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/issues/2948) has yet to support ESLint 9, which makes it a bit hard to dogfood this plugin given that it seems like the new config format is not backwards compatible with the old config format, making it hard to upgrade to ESLint 9 in this package.

Holding off on working on this until the other plugins includes support.

**Comment by Crownpack07** [comment]
@Limegrass It seems the mentioned dependencies have been upgraded to support ESLint 9, is this something that you would be able to address now?

**Comment by Limegrass** [comment]
Ah, thanks for the heads up! I'll make some time to take a look into this.

**Comment by Crownpack07** [comment]
@Limegrass Do you want me to take a look at this when I have some time? We are currently using this in our application and this plugin is preventing us from upgrading to ESLint 9, so I do not mind taking a look at it if I have some spare time this week

**Comment by Crownpack07** [comment]
I started the upgrade process, just sorting out a jest config issue post upgrade, but should be able to create a PR by end of the week if all goes well

**Comment by Crownpack07** [comment]
@Limegrass I have created a PR but it still requires a lot of refinement #18

**Comment by Limegrass** [comment]
Thanks for this. Will take a look and test this out; I'll probably have some questions just from a glance

**Comment by Limegrass** [comment]
Looks like there's a few hundred downloads for the new version and I haven't heard anything. Worked for my own usages. Closing this out for now.
