### ISSUE TITLE
Check with @jamsuu fork on improvements

### ISSUE THREAD

**Issue by Limegrass** [Limegrass/eslint-plugin-import-alias#5]
Hey @jamsuu,

I saw you had a fork which changed the glob match to an exact match, and I was just wondering what issues were you or your team facing?
Of course you are free to fork as you please, but I just wanted to get more information on whether I should include exact matching as a configuration to the lint rule as well inspired from your changes, or if you were interested in contributing it back?

Wasn't sure the best way to reach out, so I figured a tag on an issue might be most appropriate.

**Comment by jamsuu** [comment]
Hi, we had a problem where the path would conflict with the alias (eg: app/* conflicted with application-summary/...) and would not process paths under that directory. I'd be more than happy to bring the code back to this package instead, was just trying to not be too much of a bother at the time.

**Comment by Limegrass** [comment]
Ah of course, that makes sense. Thanks! You could feel free to PR it, otherwise I'll probably work on it sometime this weekend.

**Comment by Limegrass** [comment]
Whoops, looks like I missed tagging 1477ced8686cd4e9ae41aeb55eda5abcdcf5df16 as a part of this fix as well, which I believe is the change jamsuu made for their end. 83508b1 is the other fix (already tagged)
