### ISSUE TITLE
Imports of few levels

### ISSUE THREAD

**Issue by Gudaites** [Limegrass/eslint-plugin-import-alias#7]
How could I accept imports of few levels, example: './example' instead of '@root/src/module/example'

i try this

`"@limegrass/import-alias/import-alias": [
      "error",
      {
        "relativeDepth": 1
      }
    ], `

**Comment by Limegrass** [comment]
Hi Gudaites,

Currently that's not possible, but that is a great suggestion. I'll see if I could work that in as an option!

**Comment by Limegrass** [comment]
Hi Gudaites,

you should now be able to specify a configuration like
```
{
    // ...
    "rules": {
        // ...
        "@limegrass/import-alias/import-alias": [
            "error",
            {
                "relativeImportOverrides": [{ "path": ".", "depth": 0 }]
            }
        ]
    }
}
```
to enable relative imports for the entire project.

The new configuration parameter has some additional documentation on [its rules page](https://github.com/Limegrass/eslint-plugin-import-alias/blob/main/docs/rules/import-alias.md) as well, if that helps.

Let me know if that resolves your issues or if you hit any bugs with the implementation, and feel free to reopen if it didn't address your use case.
